version: "3"

volumes:
  db-data:

services:
  web:
    image: nginx:${NGINX_VERSION}
    ports:
      - "8080:80"
    volumes:
      - "./source:/var/www/html/source"
      - "./nginx/default.conf:/etc/nginx/conf.d/default.conf"
    tty: true
    stdin_open: true
    depends_on:
      - app
  app:
    build: "./php"
    volumes:
      - "./source:/var/www/html/source"
    depends_on:
      - db
    links:
      - db
  db:
    image: mysql:${MYSQL_VERSION}
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASS}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASS}
      TZ: Asia/Tokyo
    ports:
      - "3306:3306"
    volumes:
      - "db-data:/var/lib/mysql"
  phpmyadmin:
    image: phpmyadmin:${PHPMYADMIN_VERSION}
    ports:
      - "7070:80"
    depends_on:
      - db
    links:
      - db
