version: "3"

services:
  web:
    image: nginx:${NGINX_VERSION}
    ports:
      - "8080:80"
    volumes:
      - "./knowledge-note:/var/www/html/knowledge-note"
      - "./nginx/default.conf:/etc/nginx/conf.d/default.conf"
    tty: true
    stdin_open: true
    depends_on:
      - app
  app:
    build: "./php"
    volumes:
      - "./knowledge-note:/var/www/html/knowledge-note"
    depends_on:
      - db
    links:
      - db
  db:
    image: mysql:${MYSQL_VERSION}
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASS}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASS}
      TZ: Asia/Tokyo
    ports:
      - "3306:3306"
    volumes:
      - "./mysql/data:/var/lib/mysql"
  redis:
    image: redis:${REDIS_VERSION}
    ports:
        - "6379:6379"
